### ISSUE TITLE
feedback: images, cant remove tab

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_help#5]
http://160.36.205.61:8095/content/accessing-data?help_pane=help-tabs--tab_1

* I added a third tab that maybe i dont need.  There's no button to remove a tab.

* How should we handle images?  Add them separately in Drupal?  Or can we just put them in /sites/default/files or something. I dont suppose theres anyway we can make this easier?

**Comment by almasaeed2010** [comment]
- The tab is supposed to disappear if you save with empty content but that's not working for some reason. I'll look into it.
- I don't think want to create a complex image upload and placement editor. But if we can find a module that adds a better editor we can use it. Otherwise, We'd have to place images in `sites/default/files/[custom-dir]` then link to it using `<img src"/sites/default/files/path/img.png" alt="description of image for google"/>`

**Comment by almasaeed2010** [comment]
Looking at the available drupal text editors, nothing out there for drupal 7 that supports image upload. I suggest packing everything you want into a folder and uplaoding it to `sites/default/files/folder`.

**Comment by bradfordcondon** [comment]
ok no problem.

This is easy because the wiki doesnt support easy file upload either, so I've got them all on the [HWG wiki site](https://github.com/mestato/statonlabprivate/tree/master/help_docs)
